[workspace]
members = [
  "rea-rs",
  "low",
  "macros",
  "test",
]

[workspace.dependencies]
bitflags = "1.3"
bitvec = "1"
c_str_macro = "1.0.2"
env_logger = "0.10"
int-enum = "0.5"
log = "0.4"
rmp-serde = "1.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
