[package]
edition = "2021"
name = "reaper-test-extension-plugin"
publish = false
version = "1.0.0"

[dependencies]
env_logger = "0.10"
log = "0.4"
rea-rs = { version = "=1.0.0", path = "../rea-rs", features = ["egui-baseview"] }
rea-rs-low = { version = "=1.0.0", path = "../low" }
rea-rs-macros = { version = "=1.0.0", path = "../macros" }
rea-rs-test = { version = "=1.0.0", path = "../rea-rs-test" }

anyhow = {workspace = true}

[lib]
crate-type = ["cdylib"]
name = "reaper_test_extension_plugin"
