[package]
edition = "2021"
name = "rea-rs"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = {workspace = true}
c_str_macro = {workspace = true}
env_logger = {workspace = true}
int-enum = {workspace = true}
log = {workspace = true}
reaper-low = {workspace = true}
reaper-medium = {workspace = true}
rmp-serde = {workspace = true}
serde = {workspace = true}
serde_derive = {workspace = true}
serde_json = {workspace = true}

[lib]
name = "rea_rs"
