[package]
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>", "Timofei Kazantsev aka Levitanus <pianoist@ya.ru>"]
description = "Library for testing REAPER extension plug-ins within a real REAPER instance."
edition = "2021"
keywords = ["reaper", "daw", "plug-in", "audio", "midi"]
license = "MIT"
name = "rea-rs-test"
readme = "README.md"
repository = "https://github.com/Levitanus/rea-rs"
rust-version = "1.82"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rea-rs = {version = "=1.0.0", path = "../rea-rs"}
rea-rs-low = {version = "=1.0.0", path = "../low"}

anyhow = {workspace = true}
fs_extra = "1.3.0"
reqwest = {version = "0.11", features = ["blocking"]}
rust-ini = "0.21.3"
tar = "0.4.26"
wait-timeout = "0.1.5"
xz2 = "0.1"

[dev-dependencies]
rea-rs-macros = {version = "=1.0.0", path = "../macros"}
