name: Windows build only

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --workspace --verbose
    - name: Run unit and library tests
      run: cargo test --workspace --exclude reaper-test-extension-plugin --verbose
    # - name: Run REAPER integration test
    #   run: cargo test -p reaper-test-extension-plugin --test integration_test --verbose
